name: Desktop Brewery - Build Images

on:
  push:
    branches: [ "main" ]
    paths:
      - 'images/**'
      - '.github/workflows/**'
  schedule:
    - cron: '0 0 * * 0' # Weekly build on Sunday
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: debian-testing-kde
            context: ./images/debian-testing-kde
            image: desktop-debian-testing-kde
            test_command: "/usr/bin/startplasma-wayland --version"
          - name: debian-sid-gnome
            context: ./images/debian-sid-gnome
            image: desktop-debian-sid-gnome
            test_command: "/usr/bin/gnome-session --version"
          - name: ubuntu-stable
            context: ./images/ubuntu-stable
            image: desktop-ubuntu-stable
            test_command: "/usr/bin/gnome-session --version"
          - name: pop-os-cosmic
            context: ./images/pop-os-cosmic
            image: desktop-pop-os-cosmic
            test_command: "test -x /usr/bin/cosmic-session"
          - name: elementary-pantheon
            context: ./images/elementary-pantheon
            image: desktop-elementary-pantheon
            test_command: "test -x /usr/bin/io.elementary.desktop-session"
          - name: fedora-cosmic
            context: ./images/fedora-cosmic
            image: desktop-fedora-cosmic
            test_command: "test -x /usr/bin/cosmic-session"
          - name: opensuse-tumbleweed
            context: ./images/opensuse-tumbleweed
            image: desktop-opensuse-tumbleweed
            test_command: "/usr/bin/startplasma-wayland --version"
          - name: arch-kde
            context: ./images/arch-kde
            image: desktop-arch-kde
            test_command: "/usr/bin/startplasma-wayland --version"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.image }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Smoke Test Image
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.image }}:latest ${{ matrix.test_command }}
